### ISSUE TITLE
Crashing gnome shell

### ISSUE THREAD

**Issue by tuping** [machida-mn/dropbox-indicator#1]
Hello, I dont know if you are reading the ratings from extension gnome shell site.

This extension has become a crash bomb. I installed on my system and the only think that it does is to freeze the system.

I dont know if you want to keep up with the development of the extension. I think if you dont want to develop it anymore the best option is to remove it from the gnome shell extension site.

But if you want to develop it there is a good comment from there made by ferdnyc
"
This is VERY inefficiently coded — it's going to run the `dropbox running` command every two seconds, which requires starting up an entire python runtime just to check whether the daemon is running. Even if it doesn't crash, that's just not a workable way to implement a Dropbox indicator. (And if you look at the dropbox command's is_dropbox_running() method, it's fairly simple and could easily be reimplemented in JavaScript, to work directly in the Shell without having to launch any external process. All it does is read the $HOME/.dropbox/dropbox.pid file, then check /proc/$pid/cmdline to see if the string "dropbox" is present in the commandline.)
"

**Comment by machida-mn** [comment]
Thank you for reporting the bugs.

This extension have not been maintained recently because I no longer use GNOME shell.
So I made this extension inactivated. However, I was not able to remove it completely from the extension site. It may appear on search results, but you cannot install it anymore.

This repository will also be deleted in order not to spread the invalid code.
